

services:
  joblog-jenkins:
    build:
      context: .
      dockerfile: jenkins-docker.Dockerfile
    container_name: joblog-jenkins
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "9090:8080"          # Jenkins 접근 포트 (localhost:9090)
    volumes:
      - jenkins-data:/var/jenkins_home  # Jenkins 설정 유지
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 컨트롤 권한 부여
    restart: always
    user: root   # 권한 이슈 방지
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
    networks:
      - joblog