version: '3.8'

services:
  joblog-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: joblog-app
    depends_on:
      joblog-mysql:
        condition: service_healthy
      joblog-redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: ${ENV_FILE}
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    restart: always
    networks:
      - joblog