spring:
  data:
    redis:
      host: localhost
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_SECRET}
          kakao:
            client-id: ${KAKAO_ID}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password:
    driver-class-name: ${DB_DRIVER}
