spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

logging.level:
  org.hibernate:
    SQL: debug
jwt:
  secret: my-super-secret-key-that-is-long-enough-to-work
