spring:
  data:
    redis:
      host: joblog-redis
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test_google_id
            client-secret: test_google_secret
          naver:
            client-id: test_naver_id
            client-secret: test_naver_secret
          kakao:
            client-id: test_kakao_id
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE  # 인메모리 H2 DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
