spring:
  data:
    redis:
      host: localhost
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 30928436558-19oibfolu64vg7426jvoaajgjf2pcdj6.apps.googleusercontent.com
            client-secret: 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
          naver:
            client-id: VzAqaraWMceZqNQWQpIK
            client-secret: pYIPzSPxq9
          kakao:
            client-id: 9926f34f7be4a90bcdb37d01fb29fda0
  datasource:
    url: jdbc:h2:tcp://localhost/~/joblog
    driver-class-name: org.h2.Driver
    username: sa
    password:
