spring:
  data:
    redis:
      host: joblog-redis
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_SECRET}
          kakao:
            client-id: ${KAKAO_ID}
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: ${MYSQL_DRIVER}
