services:
  joblog-jenkins:
    build:
      context: .
      dockerfile: jenkins-docker.Dockerfile
    container_name: joblog-jenkins
#    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"     # Jenkins 웹
      - "50000:50000"   # 에이전트용
    volumes:
      - ~/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 컨트롤 권한 부여
    restart: unless-stopped